# Generated by Django 4.2.4 on 2023-09-05 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='目標')),
                ('from_date', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('until_date', models.DateField(blank=True, null=True, verbose_name='期日')),
                ('remind_at', models.TimeField(blank=True, null=True, verbose_name='リマインド時間')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('from_date', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('until_date', models.DateField(blank=True, null=True, verbose_name='期日')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('timer', models.IntegerField(blank=True, null=True, verbose_name='タイマー')),
                ('type', models.IntegerField(default=0, verbose_name='タイプ')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='合計')),
                ('current', models.IntegerField(blank=True, null=True, verbose_name='進捗')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('state', models.IntegerField(default=1, verbose_name='状態')),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.goals')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('todo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todos')),
            ],
        ),
    ]
