# Generated by Django 4.2.4 on 2023-09-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todos_image_alter_todos_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='memo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='current',
            field=models.IntegerField(default=0, verbose_name='進捗'),
        ),
    ]
