# Generated by Django 4.2.4 on 2023-09-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_records_memo_alter_todos_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='unit',
            field=models.CharField(default='', max_length=20, verbose_name='単位'),
        ),
    ]
