# Generated by Django 4.2.4 on 2023-09-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todos_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='type',
            field=models.CharField(default='task', max_length=20, verbose_name='タイプ'),
        ),
    ]
