# Generated by Django 4.2.4 on 2023-09-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_dream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dream',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='なりたい自分'),
        ),
    ]
